--------------------------------------------------------
--  Datei erstellt -Samstag-März-07-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARMOR_CHARACTER
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."ARMOR_CHARACTER" 
   (	"ITEMARMORNAME" VARCHAR2(26 BYTE), 
	"ITEM_ARMOR_ID" NUMBER(38,0), 
	"CLASS" VARCHAR2(26 BYTE), 
	"SLOT" VARCHAR2(26 BYTE), 
	"RARITY" VARCHAR2(26 BYTE), 
	"HPBONUS" NUMBER(38,0), 
	"SHIELDBONUS" NUMBER(38,0), 
	"MANABONUS" NUMBER(38,0), 
	"SPELLBONUS" NUMBER(38,0), 
	"ATTACKBONUS" NUMBER(38,0), 
	"CRITCHANCEBONUS" NUMBER(38,0), 
	"SPECIALEFFECT" VARCHAR2(128 BYTE), 
	"LEVELREQUIRED" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHEST_LOOT
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."CHEST_LOOT" 
   (	"CHESTTYPE" VARCHAR2(26 BYTE), 
	"ITEMNAME" VARCHAR2(26 BYTE), 
	"DROPCHANCE" VARCHAR2(26 BYTE), 
	"RARITY" VARCHAR2(26 BYTE), 
	"ITEMTYPE" VARCHAR2(26 BYTE), 
	"GOLDMIN" NUMBER(38,0), 
	"GOLDMAX" NUMBER(38,0), 
	"CHEST_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONSUMABLES
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."CONSUMABLES" 
   (	"ITEMNAME" VARCHAR2(128 BYTE), 
	"ITEM_ID" NUMBER(38,0), 
	"TYPE" VARCHAR2(26 BYTE), 
	"RARITY" VARCHAR2(26 BYTE), 
	"HP_RESTORE" NUMBER(38,0), 
	"MANA_RESTORE" NUMBER(38,0), 
	"RAGE_RESTORE" NUMBER(38,0), 
	"ENERGY_RESTORE" NUMBER(38,0), 
	"ATTACK_BUFF" NUMBER(38,0), 
	"SPELL_BUFF" NUMBER(38,0), 
	"CRIT_BUFF" VARCHAR2(26 BYTE), 
	"DEFENSE_BUFF" NUMBER(38,0), 
	"DURATION_TURNS" NUMBER(38,0), 
	"COOLDOWN_TURNS" NUMBER(38,0), 
	"REMOVES_POISON" NUMBER(38,0), 
	"REMOVES_FEAR" NUMBER(38,0), 
	"LEVELREQUIRED" NUMBER(38,0), 
	"GOLDVALUE" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CREATURES
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."CREATURES" 
   (	"CREATURE_ID" NUMBER(38,0), 
	"NAME" VARCHAR2(26 BYTE), 
	"TYPE" VARCHAR2(26 BYTE), 
	"INDICATORS" VARCHAR2(26 BYTE), 
	"ARMOR" VARCHAR2(26 BYTE), 
	"WEAPONS" VARCHAR2(128 BYTE), 
	"TALENTS" VARCHAR2(128 BYTE), 
	"HP" NUMBER(38,0), 
	"SHIELD" NUMBER(38,0), 
	"MANA" NUMBER(38,0), 
	"SPELL" NUMBER(38,0), 
	"ATTACK" NUMBER(38,0), 
	"CRIT_HIT" VARCHAR2(26 BYTE), 
	"CRIT_CHANCE" VARCHAR2(26 BYTE), 
	"RAGE" NUMBER(38,0), 
	"ENERGY" NUMBER(38,0), 
	"CONCENTRATION" NUMBER(38,0), 
	"RAGE_GENERATION" NUMBER(38,0), 
	"ENRAGE_THRESHOLD" NUMBER(38,0), 
	"BLEED_CHANCE" NUMBER(38,0), 
	"SPEED_BONUS" NUMBER(38,0), 
	"ESCAPE_CHANCE" NUMBER(38,0), 
	"FEAR_CHANCE" NUMBER(38,0), 
	"FIRE_RESISTANCE" NUMBER(38,0), 
	"FIRE_IMMUNITY" NUMBER(38,0), 
	"DARK_DAMAGE_BONUS" NUMBER(38,0), 
	"PHYSICAL_RESISTANCE" NUMBER(38,0), 
	"SLOW_EFFECT" NUMBER(38,0), 
	"ARMOR_BONUS" NUMBER(38,0), 
	"STUN_CHANCE" NUMBER(38,0), 
	"POISON_CHANCE" NUMBER(38,0), 
	"SUMMON_SWARM" NUMBER(38,0), 
	"LIFE_DRAIN" NUMBER(38,0), 
	"UNDEAD_REGENERATION" NUMBER(38,0), 
	"OVERHEAT_MODE" NUMBER(38,0), 
	"HEALING_POWER" NUMBER(38,0), 
	"PET_BONUS_DAMAGE" NUMBER(38,0), 
	"ELEMENTAL_BONUS" NUMBER(38,0), 
	"REWARD_EXP_MIN" NUMBER(38,0), 
	"REWARD_EXP_MAX" NUMBER(38,0), 
	"REWARD_GOLD_MIN" NUMBER(38,0), 
	"REWARD_GOLD_MAX" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CREATURES_LOOT
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."CREATURES_LOOT" 
   (	"ENEMYNAME" VARCHAR2(26 BYTE), 
	"ITEMNAME" VARCHAR2(256 BYTE), 
	"DROPCHANCE" NUMBER(38,0), 
	"RARITY" VARCHAR2(128 BYTE), 
	"ITEMTYPE" VARCHAR2(128 BYTE), 
	"EXP_MIN" VARCHAR2(128 BYTE), 
	"EXP_MAX" VARCHAR2(128 BYTE), 
	"GOLD_MIN" VARCHAR2(128 BYTE), 
	"GOLD_MAX" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENCHANTMENTS
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."ENCHANTMENTS" 
   (	"ENCHANTNAME" VARCHAR2(26 BYTE), 
	"ENCHANT_ID" NUMBER(38,0), 
	"SLOTTYPE" VARCHAR2(26 BYTE), 
	"RARITY" VARCHAR2(26 BYTE), 
	"ATTACKBONUS" NUMBER(38,0), 
	"SPELLBONUS" NUMBER(38,0), 
	"HPBONUS" NUMBER(38,0), 
	"SHIELDBONUS" NUMBER(38,0), 
	"CRITCHANCEBONUS" VARCHAR2(26 BYTE), 
	"CRITDAMAGEBONUS" VARCHAR2(26 BYTE), 
	"ELEMENTTYPE" VARCHAR2(26 BYTE), 
	"ELEMENTBONUS" NUMBER(38,0), 
	"SPECIALEFFECT" VARCHAR2(128 BYTE), 
	"LEVELREQUIRED" NUMBER(38,0), 
	"GOLDCOST" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GEMS
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."GEMS" 
   (	"GEMNAME" VARCHAR2(26 BYTE), 
	"GEM_ID" NUMBER(38,0), 
	"CATEGORY" VARCHAR2(26 BYTE), 
	"RARITY" VARCHAR2(26 BYTE), 
	"SOCKETTYPE" VARCHAR2(26 BYTE), 
	"ATTACKBONUS" NUMBER(38,0), 
	"SPELLBONUS" NUMBER(38,0), 
	"HPBONUS" NUMBER(38,0), 
	"SHIELDBONUS" NUMBER(38,0), 
	"CRITCHANCEBONUS" NUMBER(38,0), 
	"CRITDAMAGEBONUS" VARCHAR2(26 BYTE), 
	"ELEMENTTYPE" VARCHAR2(26 BYTE), 
	"ELEMENTBONUS" NUMBER(38,0), 
	"LEVELREQUIRED" NUMBER(38,0), 
	"GOLDVALUE" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATIONS
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."LOCATIONS" 
   (	"LOCATION" VARCHAR2(26 BYTE), 
	"MOBS" VARCHAR2(128 BYTE), 
	"CHESTS" VARCHAR2(26 BYTE), 
	"CHANCE_FOR_MOB" VARCHAR2(26 BYTE), 
	"CHANCE_FOR_CHEST" VARCHAR2(38 BYTE), 
	"LOCATION_ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATERIALS
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."MATERIALS" 
   (	"MATERIALNAME" VARCHAR2(26 BYTE), 
	"MATERIAL_ID" NUMBER(38,0), 
	"CATEGORY" VARCHAR2(26 BYTE), 
	"RARITY" VARCHAR2(26 BYTE), 
	"SOURCETYPE" VARCHAR2(26 BYTE), 
	"STACKLIMIT" NUMBER(38,0), 
	"CRAFTINGTIER" NUMBER(38,0), 
	"GOLDVALUE" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAYER
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."PLAYER" 
   (	"CHARACTER_ID" NUMBER(38,0), 
	"CHARACTER" VARCHAR2(26 BYTE), 
	"TYPE" VARCHAR2(26 BYTE), 
	"INDICATORS" VARCHAR2(26 BYTE), 
	"ARMOR" VARCHAR2(26 BYTE), 
	"WEAPONS" VARCHAR2(128 BYTE), 
	"TALENTS" VARCHAR2(128 BYTE), 
	"HP" NUMBER(38,0), 
	"SHIELD" NUMBER(38,0), 
	"MANA" NUMBER(38,0), 
	"SPELL" NUMBER(38,0), 
	"ATTACK" NUMBER(38,0), 
	"CRIT_HIT" VARCHAR2(26 BYTE), 
	"CRIT_CHANCE" VARCHAR2(26 BYTE), 
	"RAGE_GENERATION" VARCHAR2(26 BYTE), 
	"PET_BONUS_DAMAGE" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QUESTS
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."QUESTS" 
   (	"QUESTNAME" VARCHAR2(26 BYTE), 
	"QUEST_ID" NUMBER(38,0), 
	"DESCRIPTION" VARCHAR2(128 BYTE), 
	"OBJECTIVE" VARCHAR2(128 BYTE), 
	"REQUIREDLEVEL" NUMBER(38,0), 
	"REWARD_EXP" NUMBER(38,0), 
	"REWARD_GOLD" NUMBER(38,0), 
	"REWARD_CHEST" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WEAPONS_CHARACTER
--------------------------------------------------------

  CREATE TABLE "C##CONSOLE_SPIEL_USER"."WEAPONS_CHARACTER" 
   (	"WEAPONNAME" VARCHAR2(26 BYTE), 
	"WEAPON_ID" NUMBER(38,0), 
	"CLASS" VARCHAR2(26 BYTE), 
	"WEAPONTYPE" VARCHAR2(26 BYTE), 
	"RARITY" VARCHAR2(26 BYTE), 
	"ATTACKBONUS" NUMBER(38,0), 
	"SPELLBONUS" NUMBER(38,0), 
	"CRITCHANCEBONUS" VARCHAR2(26 BYTE), 
	"SPECIALEFFECT" VARCHAR2(128 BYTE), 
	"LEVELREQUIRED" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ARMOR_CHARACTER
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ARMOR_CHARACTER" MODIFY ("ITEMARMORNAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ARMOR_CHARACTER" MODIFY ("ITEM_ARMOR_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ARMOR_CHARACTER" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ARMOR_CHARACTER" MODIFY ("SLOT" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ARMOR_CHARACTER" MODIFY ("RARITY" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ARMOR_CHARACTER" MODIFY ("HPBONUS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ARMOR_CHARACTER" MODIFY ("SHIELDBONUS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ARMOR_CHARACTER" MODIFY ("SPECIALEFFECT" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ARMOR_CHARACTER" MODIFY ("LEVELREQUIRED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHEST_LOOT
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CHEST_LOOT" MODIFY ("CHESTTYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CHEST_LOOT" MODIFY ("ITEMNAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CHEST_LOOT" MODIFY ("DROPCHANCE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CHEST_LOOT" MODIFY ("RARITY" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CHEST_LOOT" MODIFY ("ITEMTYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CHEST_LOOT" MODIFY ("GOLDMIN" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CHEST_LOOT" MODIFY ("GOLDMAX" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CHEST_LOOT" MODIFY ("CHEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONSUMABLES
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CONSUMABLES" MODIFY ("ITEMNAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CONSUMABLES" MODIFY ("ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CONSUMABLES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CONSUMABLES" MODIFY ("RARITY" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CONSUMABLES" MODIFY ("LEVELREQUIRED" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CONSUMABLES" MODIFY ("GOLDVALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CREATURES
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES" MODIFY ("CREATURE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES" MODIFY ("INDICATORS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES" MODIFY ("WEAPONS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES" MODIFY ("TALENTS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES" MODIFY ("ATTACK" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES" MODIFY ("CRIT_HIT" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES" MODIFY ("CRIT_CHANCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CREATURES_LOOT
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES_LOOT" MODIFY ("ENEMYNAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES_LOOT" MODIFY ("ITEMNAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES_LOOT" MODIFY ("DROPCHANCE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES_LOOT" MODIFY ("RARITY" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES_LOOT" MODIFY ("ITEMTYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES_LOOT" MODIFY ("EXP_MIN" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES_LOOT" MODIFY ("EXP_MAX" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES_LOOT" MODIFY ("GOLD_MIN" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."CREATURES_LOOT" MODIFY ("GOLD_MAX" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENCHANTMENTS
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ENCHANTMENTS" MODIFY ("ENCHANTNAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ENCHANTMENTS" MODIFY ("ENCHANT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ENCHANTMENTS" MODIFY ("SLOTTYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ENCHANTMENTS" MODIFY ("RARITY" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ENCHANTMENTS" MODIFY ("ELEMENTTYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ENCHANTMENTS" MODIFY ("SPECIALEFFECT" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ENCHANTMENTS" MODIFY ("LEVELREQUIRED" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."ENCHANTMENTS" MODIFY ("GOLDCOST" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GEMS
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."GEMS" MODIFY ("GEMNAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."GEMS" MODIFY ("GEM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."GEMS" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."GEMS" MODIFY ("RARITY" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."GEMS" MODIFY ("SOCKETTYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."GEMS" MODIFY ("ELEMENTTYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."GEMS" MODIFY ("LEVELREQUIRED" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."GEMS" MODIFY ("GOLDVALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATIONS
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."LOCATIONS" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."LOCATIONS" MODIFY ("MOBS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."LOCATIONS" MODIFY ("CHESTS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."LOCATIONS" MODIFY ("CHANCE_FOR_CHEST" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."LOCATIONS" MODIFY ("LOCATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIALS
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."MATERIALS" MODIFY ("MATERIALNAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."MATERIALS" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."MATERIALS" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."MATERIALS" MODIFY ("RARITY" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."MATERIALS" MODIFY ("SOURCETYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."MATERIALS" MODIFY ("STACKLIMIT" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."MATERIALS" MODIFY ("CRAFTINGTIER" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."MATERIALS" MODIFY ("GOLDVALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAYER
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."PLAYER" MODIFY ("CHARACTER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."PLAYER" MODIFY ("CHARACTER" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."PLAYER" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."PLAYER" MODIFY ("INDICATORS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."PLAYER" MODIFY ("ARMOR" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."PLAYER" MODIFY ("WEAPONS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."PLAYER" MODIFY ("TALENTS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUESTS
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."QUESTS" MODIFY ("QUESTNAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."QUESTS" MODIFY ("QUEST_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."QUESTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."QUESTS" MODIFY ("OBJECTIVE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."QUESTS" MODIFY ("REQUIREDLEVEL" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."QUESTS" MODIFY ("REWARD_EXP" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."QUESTS" MODIFY ("REWARD_GOLD" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."QUESTS" MODIFY ("REWARD_CHEST" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WEAPONS_CHARACTER
--------------------------------------------------------

  ALTER TABLE "C##CONSOLE_SPIEL_USER"."WEAPONS_CHARACTER" MODIFY ("WEAPONNAME" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."WEAPONS_CHARACTER" MODIFY ("WEAPON_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."WEAPONS_CHARACTER" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."WEAPONS_CHARACTER" MODIFY ("WEAPONTYPE" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."WEAPONS_CHARACTER" MODIFY ("RARITY" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."WEAPONS_CHARACTER" MODIFY ("ATTACKBONUS" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."WEAPONS_CHARACTER" MODIFY ("SPECIALEFFECT" NOT NULL ENABLE);
  ALTER TABLE "C##CONSOLE_SPIEL_USER"."WEAPONS_CHARACTER" MODIFY ("LEVELREQUIRED" NOT NULL ENABLE);
